"""Add user tokens

Revision ID: 987cba146d3b
Revises: 241eb046f354
Create Date: 2025-07-27 16:04:14.122530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '987cba146d3b'
down_revision = '241eb046f354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_token'))
        batch_op.drop_column('token')

    # ### end Alembic commands ###
